language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - protobuf-compiler
    - build-essential

before_install:
  - ./build.sh

install:
  - pip install tox-travis coverage

script:
  - tox

after_success:
  - coverage combine tests/
  - bash <(curl -s https://codecov.io/bash)
