import os

__version__ = "0.0.15rc1"
BLOCKCHAIN_NAME = "lbrycrd_main"
BLOCKCHAIN_NAME_ENVVAR = "LBRYSCHEMA_BLOCKCHAIN_NAME"
if BLOCKCHAIN_NAME_ENVVAR in os.environ:
    BLOCKCHAIN_NAME = os.environ[BLOCKCHAIN_NAME_ENVVAR]
